Update 15_obia.R
Update deprecated randomForest to smileRandomForest to fix error: 
EEException: Classifier.randomForest: This classifier has been replaced.  For more information see: http://goo.gle/deprecated-classifiers.